### ISSUE TITLE
Blog post to announce our May 2022 Outreachy interns

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/openrefine.github.com#105]
Publish blog post to announce our 2022 Outreachy interns.

**Comment by trnstlntk** [comment]
Hmm, @wetneb I'm not seeing the blog post appear in https://openrefine.org/category/blog.html ... what could be wrong?

**Comment by wetneb** [comment]
The date of your blog post was still in the future when the PR was merged, and that prevented the blog post from appearing publicly. I have just made an unrelated edit elsewhere in the repository so that the website is regenerated, which should make the post appear.
