### ISSUE TITLE
Two-week test period for Discourse forum

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/openrefine.github.com#118]
It seems that our community has no major objections against moving OpenRefine's mailing lists to Discourse; see [thread on our user mailing list](https://groups.google.com/g/openrefine/c/mFD3VC0UZxQ) and [a larger document with considerations around this move](https://docs.google.com/document/d/1PY0T6dudVO6iQAbf1EUEdL1UTHu7eSFamJjL22ELMEI/edit).

So I suggest we go ahead with a two-week test period. Let's use this issue for discussion as long as we can't use the forum yet.

**Comment by trnstlntk** [comment]
Pinging everyone who has expressed interest in the move, have been engaged in brainstorming about it, and some more people ;-) @wetneb @ostephens @magdmartin @ainali

I'm also taking the freedom to ping other people who are currently quite active in our community and whose input would be very welcome (if you want) @Abbe98 @elebitzero @antoine2711 @tfmorris @susannaanas

All, please chime in re: timing and your availability IF you want to help.

**Comment by trnstlntk** [comment]
I will be quite busy this month of October 2022 (ending the SDC project and doing a lot of documentation work) and until end October I'd prefer to only do lightweight / basic admin stuff. In November I will have more time.
If some of you want to do the majority of testing now: I'd be very happy with that, supporting mostly in lightweight administrative ways.

I can do:

- [ ] Setting up the general account and making sure it's connected to OpenRefine's credit card. As said, we will go for the cheapest paid option: standard plan with non-profit discount. I will also arrange the discount (it will need a bit of arranging)
- [ ] Making sure everyone who wants can create accounts and gets admin rights
- [ ] Some lightweight playing with the forum structure (in November I will have more time for that)

For now, do we want other communications channels than this one?

**Comment by ostephens** [comment]
Very happy to be involved. No particular timing for me - I'll make time as necessary

**Comment by trnstlntk** [comment]
Re: admins/moderators: my understanding (but we need to test) is that Discourse helps with this process by itself: it will automatically give more rights to people who contribute usefully (e.g. get lots of likes/appreciation).

That said, yes, we should actively recruit moderators from different backgrounds. That will also happen with the changes in governance we'll introduce in a few months (stay tuned, I will blog about that as soon as I get to it).

**Comment by Stonepeople** [comment]
I am interested in helping, in moderation or whatever. No previous experience of moderatoin, I am just a heavy user of OR, and data-related stuff in general.

**Comment by trnstlntk** [comment]
Test period has passed, but we (at least I) can still access the test link.

It seems I have succeeded in setting up https://forum.openrefine.org/ as a URL pointing to it. And it's now named OpenRefine (not OpenRefine Test).

Shall we continue working with this current installation, silently setting it up for the actual transition? I could set up a new account with Discourse but don't see why we wouldn't continue working with the current one. We can remove the nonsensical tests discussions and start setting up the thing 'for good'. On my side, I can start the recurring monthly payment process.

**Comment by wetneb** [comment]
> I was kind of hoping that if I ignored this that it'd go away, since our current communications mechanisms are a) free and b) appear to work just fine, but it looks like there's a risk that we're going to have to migrate to a new non-free web app after all.

Google Groups is free as in free beer. It is closed source though. Also its UI basically forces people to sign up with a GMail account: the possibility to sign up with other email providers is very much hidden and that is a really unhealthy practice.

From distinct people I heard those things:
* people who do not sign up to the mailing lists on principle, because they are hosted on Google Groups
* people who just assume that if a communication forum is hosted on Google Groups, the corresponding project is likely dormant

> mailing list archive - a previous doc claimed that it could/would be imported, but I don't see it

The tendency now is that although it would be possible to do it, we are tempted to decide against. Importing content in a different platform comes with various problems: the content does not quite fit the data model of the new platform, and the users did not necessarily expect to see their content being published in another platform. The Google Group should stay accessible as an archive regardless.

> In my experience, tooling makes a very minor difference in the vitality of a community

I disagree here. Do you think OpenRefine would be in the same place if its source code had been hosted on SourceForge instead of GitHub for the past few years? The platform makes a huge difference in how people interact with the project, and simply their productivity! This is the same for discussions, you get totally different interactions depending on how the platform structures them.

Among the features I find important (with my very limited testing so far):
* Mailing lists have no built-in way to categorize threads - this is such a basic need! Some people are held back by the idea that they are messaging a big community indiscriminately and do not post much on mailing lists because of that.
* Discourse has much better moderation features

**Comment by magdmartin** [comment]
I suggest we purge all the messages published during the test period and
have a clean start.

I also notice this background under awesome public dataset (
https://forum.openrefine.org/t/awesome-public-datasets/17) which make the
text hard to read. I think this is something we can fix as we move ahead.

**Comment by thadguidry** [comment]
> We can remove the nonsensical tests discussions and start setting up the
thing 'for good'.

Great, thank you Sandra.
As to Tom's comments, I think I agree fully with Antonin's reply.  This
should open doors more for our community.
I only worry about the longevity and payments/funding going forward, but
we'll figure that out if the time ever comes and maybe I'll beg Google and
we can have a lifetime of funding for it.  Isn't it discounted if paid
ahead for a full year rather than monthly?

**Comment by trnstlntk** [comment]
I have set up monthly recurring payments with the 50% nonprofit discount. The Discourse support response was flawless, fast, helpful and transparent. FYI, OpenRefine currently already receives more than USD $50 per month through GitHub donations (organically, we never advertised it). IMO we have a lot of untapped potential to cover modest baseline costs via donations.

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/9881645/196872234-7913a436-2486-4406-b067-7e454ff01b52.png">

**Comment by ostephens** [comment]
I want to just pick up on some of Tom's comments:

Firstly I sympathise with the comments about phpBB etc and agree that we can't expect a change of tool to be the one thing that encourages community. However, I agree with Antonin that tools can make a difference, and I do think that some tools are better than others. I believe that Discourse offers a better toolset than Google Groups and hope this will help us develop the community.

More practically based on Tom's other comments is it worth us looking at:

* Which sign-on mechanisms we want to support? (It looks like Github has been configured and I've used that to login, but Google, Twitter and Facebook are also options we can configure)
* Migrating the existing mailing list archive - it looks like there might be an option for doing this https://meta.discourse.org/t/migrate-a-mailing-list-to-discourse-mbox-listserv-google-groups-etc/79773 - is this something we want to do, and if not, what approach do we want to take to preserving useful discussions from the Google Groups
* TOS/Privacy - Tom raises some concern about these - is there anything that needs doing before we go ahead with the change?

**Comment by trnstlntk** [comment]
> I want to just pick up on some of Tom's comments:
> 
> Firstly I sympathise with the comments about phpBB etc (also having been there and done that!) and agree that we can't expect a change of tool to be the one thing that encourages community. However, I agree with Antonin that tools can make a difference, and I do think that some tools are better than others. I believe that Discourse offers a better toolset than Google Groups and hope this will help us develop the community.

💯 I am also ancient and weary and "have seen it all". That said, two of the communities I'm very active in have really benefited and flourished after moving to more welcoming platforms: Creative Commons (Slack; there was a lot of controversy and resistance but it has tremendously helped diversify and make the community more lively) and Wikimedia (Telegram, FB groups, various Discourse forums, some Discord - all these make more granular and safe discussion possible, help especially underrepresented groups, and have e.g. catalysed the explosive growth of Wikimedia community engagement in Africa).

> * Which sign-on mechanisms we want to support? (It looks like Github has been configured and I've used that to login, but Google, Twitter and Facebook are also options we can configure)

I'm looking into this. Every single one needs to be configured individually ([example for Google](https://meta.discourse.org/t/configure-google-login-for-discourse/15858)); they are not turned on by default but I'm setting them up as we speak.

Anyone with admin rights can see these settings and adjust them by the way. 

> * Migrating the existing mailing list archive - it looks like there might be an option for doing this https://meta.discourse.org/t/migrate-a-mailing-list-to-discourse-mbox-listserv-google-groups-etc/79773 - is this something we want to do, and if not, what approach do we want to take to preserving useful discussions from the Google Groups

My potential objections would be: 1) full import could flood the forum and 2) privacy concerns. Possibly both can be mitigated if the migration is approached with care. I'll leave it up to others to decide whether to go ahead, and to do the actual work.

> * TOS/Privacy - Tom raises some concern about these - is there anything that needs doing before we go ahead with the change?

I have just asked CS&S Legal to do a quick check of these. I assume they are thoroughly vetted already as they are the default ones used on multitudes of Discourse forums, but a check won't hurt.

**Comment by thadguidry** [comment]
I would prefer to let Discourse fill up naturally and just archive our Google Groups.  Besides, we can always login and search the Google Groups and grab Owen's sweet tips when needed and copy/paste them into the Discourse forum as the needs arise. :-)

Some reasons I would just archive Google Groups and not bother migrating:
1. A primary reason is that topics and tags are very important to us going forward with reporting and I don't see that happening well at all.  
2. We "might" hit some quota threshold for our Discourse that concerns them.

So, I say, just pick the date for closing the Google Groups after an announcement on it, perhaps 2 weeks is enough time?  We also will need to update the various spots where we mention the mailing list and say it's closed now and point them to our Discourse forum.

**Comment by wetneb** [comment]
Closing this since the test period is over and the forum is operational. The mailing lists will be read-only soon.
