### ISSUE TITLE
Complete rewrite of the website with Docusaurus

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.github.com#126]
The current state of the website makes me sad: it feels unprofessional in many ways, cluttered, outdated…
Since we now have documentation with Docusaurus, and Docusaurus also supports making websites and not just docs, I have had a go at rewriting the website in this framework.

You can have a look at the preview here: https://wetneb.github.io/new-openrefine-website/

Main goals:
* Have a consistent style, shared between the website and the docs
* Provide a much more streamlined download experience (#55)
    * Prominent download button on the main page
    * Automatic selection of the latest stable release and detection of the platform to pick the best download
    * Post download page with follow up links and running instructions
* Simplification of the release process (adding a release can be done by adding a Javascript object in a file, rather than editing a lot of HTML manually).
* Remove clutter in most pages, trimming them down to make information more findable
* Provide [a more welcoming Community page](https://wetneb.github.io/new-openrefine-website/community)
* Have fun inserting silly visuals to pimp this all up
* Fix some issues in the process: #50, #52, #53

Initially I tried to just migrate the existing content to Docusaurus without changing the content itself but it was pretty frustrating to spend time formatting content that would have to be significantly reworked, so I made a lot of editorial decisions which are of course debatable. For instance:
* Remove the Google Refine videos from the main page. They are really old now, and while they do a good job at showing the spirit of the tool, we can showcase the tool in other ways. The feature cards I added are an attempt to provide a sort of alternative (although they of course do not convey the same thing as a video).
* Remove the "Using OpenRefine" book. This resource is not freely available and was created at a time when OpenRefine did not have an official user manual. We have that now, so there is no need to advertise this paid resource anymore.
* Separate the extensions and other distributions from the download page. I think those things have a different status, since they are not maintained by the same team. It also helps de-clutter the download page quite dramatically.

The blog is also migrated, and adding new posts works pretty much in the same way as with Jekyll - just drop a Markdown file in the `blog/` subdirectory of the website, with some metadata in the header, and done.

If people like this new version, there are a couple of follow-up tasks before publication:
* Fix a bunch of broken links (detected by Docusaurus)
* Clean up images included in the blog (many of them use absolute links, we need to include the images in the source repository to make sure they don't disappear, even though Docusaurus seems to download them dynamically and include them in the static website by itself - but of course that will stop working when the images disappear)
* Set up some redirects so that the current URLs don't break - such as `https://openrefine.org/download.html -> https://openrefine.org/download` and `https://docs.openrefine.org/ -> https://openrefine.org/docs/`
* Clean up some of the React code to migrate some style directives to CSS files
* Anything else?

**Comment by thadguidry** [comment]
@wetneb 
Could use a bit of padding or maybe just wider VERSION column.  Generally just check the padding or wrapping of text in the various container elements all around your design.  Great Design by the way!
![image](https://user-images.githubusercontent.com/986438/202593818-2397fbfb-dd9f-4bf3-b01b-94b0972ff445.png)

@trnstlntk
Do we have funding to make 1 new intro video and have some mechanism that can show/play Closed Captions maybe transcribed in multiple languages - our recent grant?

**Comment by thadguidry** [comment]
@trnstlntk
Do we have funding to make 1 new intro video and have some mechanism that can show/play Closed Captions maybe transcribed in multiple languages - our recent grant? [#127 Create new intro video for OpenRefine explaining most used features](127)

**Comment by wetneb** [comment]
Thanks Thad! Yes I am also not very happy with this column. Perhaps the date is worthy of its own column, or have a line break to enforce that it is on its own line.

I am curious about the colors in your screenshot. Is that how it renders without any change on your side? The light blue is obviously too bright to be readable there.

On my side it looks like this:
![image](https://user-images.githubusercontent.com/309908/202643078-a66e98ea-a94e-4bfc-a861-e949f1cce724.png)

Even in that state I find the white over blue (and the small links below) not very readable. I just used the existing theme of the docs, but would be tempted to switch to a darker shade of blue (as defined by the existing palette).

**Comment by ostephens** [comment]
Really appreciate the work you've put in here @wetneb and I think it looks great. 

No substantive comments but just wondering about the list of versions in the download table - it seems like quite a lot of options on the page - do we need all these versions listed? I also think the two versions for Windows will continue to be slightly confusing (what does the main button default to for Windows users?)

Apart from that - I'm very happy to contribute to cleanup tasks if you want to point me towards broken links and external images

**Comment by wetneb** [comment]
Thanks @ostephens!

> No substantive comments but just wondering about the list of versions in the download table - it seems like quite a lot of options on the page - do we need all these versions listed?

We can definitely have less! Maybe 3.6.2 and 3.5.2 for now?

> I also think the two versions for Windows will continue to be slightly confusing

True… we can totally think about different presentations.

> what does the main button default to for Windows users?

The one with JRE included per https://github.com/OpenRefine/OpenRefine/issues/5257

> Apart from that - I'm very happy to contribute to cleanup tasks if you want to point me towards broken links and external images

Thanks! I am sure there will be no shortage of polishing to do ^^

**Comment by thadguidry** [comment]
> I am curious about the colors in your screenshot. Is that how it renders without any change on your side? The light blue is obviously too bright to be readable there.

@wetneb The colors render as yours does (ignore my color palette in previous screenshot - HDR screenshot bug on my end)

![image](https://user-images.githubusercontent.com/986438/202733535-8423c9f9-1e24-4108-a549-2ad20f42d19c.png)

**Comment by tfmorris** [comment]
Wow - talk about mixing style and content changes! Allowing less than a week to review a complete website rewrite and then merging it on a public holiday and 4 day weekend seems, umm, aggressive. Is there even a pull request or any approvals?

I started compiling an extensive list of comments a few days ago. I guess there's not really any reason to complete the review now that it's a _fait accompli_.

**Comment by wetneb** [comment]
Sorry that it felt aggressive to you!
I did not think there would be much point of doing one PR which would change basically all files in the repository - I do not think this is something that would bring much, as it basically cannot be reviewed as a set of changes to existing files.

I'd be very happy to have a look at your comments in any form, I am sure they would help improve the website a lot. I do not think the website needs to be perfect before it is published either. The basic idea of the migration was validated in this issue and https://github.com/OpenRefine/OpenRefine/issues/5187.

If you need a PR to formulate your comments, we could also consider reverting the move and opening a PR again for it - but again I am unsure what it would bring.

Overall, I think project members should feel invited to make bold changes to the website on their side too. I think this is a preferable situation over a de-facto abandoned website, without anyone feeling responsible for its curation. I think you noticed this state on your side too (pull requests being left without feedback for a long time and links to training materials being largely outdated, to name a few).

So please, Tom, feel free to be bold and make any changes you want!

**Comment by ostephens** [comment]
I’d probably agree that an announcement that there was going to go ahead with a timetable (even a short one) would have been a good idea. (Note that it isn’t a holiday in Europe this week and I think that the merge on a US public holiday/long weekend should be seen as bad timing rather than an aggressive move)

@wetneb I do appreciate the “be bold” approach and I do support these changes overall so I’m definitely not asking for anything to be reverted - I think we should move forward from here. But we do also need to have some level of control - constant bold changes to the website would be a bad thing I think. 

I like the changes and I think it’s a definite improvement on the old website for me and I very much appreciate the work put in by @wetneb here but I hope that @tfmorris will still offer some comments which can be used to make further improvements

**Comment by wetneb** [comment]
Makes sense, sorry again for pushing this too fast. I'll make sure I coordinate more in the future.
