### ISSUE TITLE
Update Website with link to bountysource

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.github.com#21]
[OpenRefine Bounty Source](https://www.bountysource.com/teams/openrefine) is taking off (thanks @thadguidry for setting this up!)  We have regular backers and already awarded two bounties in 2017!

I think the public website deserves a link encouraging our user to donate.

Pull Request Welcome

**Comment by thadguidry** [comment]
@magdmartin yeah, I have also been trying to socialize it more also... like my recent Google+ post about supporting Open Source Software even for a $1...blah blah.   We need others to step in and start tweeting and socializing it more

**Comment by ettorerizza** [comment]
Based on my past experience, large social networks are not the best place to organize a fundraiser for a niche project (unless it is supported by some viral content). Too much competition, too many people who are asking for money for a lot of noble causes... The best place, imho, is where people feel a sudden sympathy that drives them to get their hands on the wallet. I mean, if StackOverflow asked for $ 5 after someone earned me a half day of work, I would give 20. For Open Refine, this place could be the mailing list/Google group (and the UI itself of course).

**Comment by thadguidry** [comment]
I would only agree to OpenRefine's UI only on the index home page http://127.0.0.1:3333/  perhaps below the Diamond logo and version number.  A donate link or graphic badge with link.

**Comment by ettorerizza** [comment]
OK, @thadguidry . Just for my instruction, is there a particular reason why "you would only agree to OpenRefine's UI", and not in the Google group ? I often see in the mailing list repeated requests from a single user who wants to be helped in every step of his project. The members of the user community are all, I think, mutual helpers. But it would be tempting, at times, to emphasize that a small gift to Open Refine would be welcome as a reward for time spent solving specific problems ...

**Comment by thadguidry** [comment]
@ettorerizza you misunderstood.  I am just placing a distinct limit on where to place our donation badge in the OpenRefine "application" so that OpenRefine is not cluttered for our users.  Beyond our application...anything goes for advertising, so sure, groups, lists, social websites, etc. can and should be an advertising venue for our cause of improving OpenRefine ! :)

**Comment by ettorerizza** [comment]
I understand better. That being said, we see a lot of love for OpenRefine on Twitter (https://twitter.com/search?q=%22open%20refine%22%20love&src=typd). I do not know how to explain to these people that this software is only maintained by enthusiasts. Creating a bot that says "Give money!!!!" for each tweet "I love Open refine <3"? :D

**Comment by jackyq2015** [comment]
I am not impressed by bountysource so far. Cashed out my first bounty from them 1 month ago and still hasn't received it. Sent them 4 emails but no reply. Is there any alternatives to it?

**Comment by thadguidry** [comment]
Serious @jackyq2015  ???

**Comment by jackyq2015** [comment]
cheque. I know they process the payment every Friday which is fine. But 1 month is too much and at least they should have been responsive to the cash out inquiry.

**Comment by magdmartin** [comment]
@wetneb what is your experience to get paid via bountysource?

**Comment by magdmartin** [comment]
@jackyq2015 looks like bountysource is late for all recent cashout: https://github.com/bountysource/core/issues/1123

**Comment by jackyq2015** [comment]
@magdmartin Thanks for the information.

**Comment by magdmartin** [comment]
We decided to stop supporting bountysource
