### ISSUE TITLE
Update Website to indicate different language supported

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.github.com#22]
We should indicate on the website that OpenRefine is available in English Spanish, Italian, French, Chinese and Japanese. 

Pull Request Welcome

**Comment by wetneb** [comment]
I would be in favor of a complete overhaul of the website, with a nicer theme and fresher info.

**Comment by magdmartin** [comment]
A new website design will be nice too. I put this one together hacking on existing Jekyll theme but I am far away from being a web developer. We can start to brainstorm idea on what we'd like to see on the website via this issue tracker.
