### ISSUE TITLE
Misalignment in book topics on website

### ISSUE THREAD

**Issue by joanneong** [OpenRefine/openrefine.github.com#26]
I visited the OpenRefine's website, and saw this:

![image](https://user-images.githubusercontent.com/24493463/36040011-29ad3c1e-0dff-11e8-8e15-ed1a51f8be44.png)

which probably only requires a simple fix. However, I will be going to bed soon so I thought I'd better post this here first before I forget. Feel free to fix this in the meantime.

**Comment by magdmartin** [comment]
This is solved in the PR #27

**Comment by magdmartin** [comment]
new website deployed but the image is broken on  http://openrefine.org/documentation.html
