### ISSUE TITLE
HTTPS for openrefine.org

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.github.com#36]
Following remarks from  @nilswindisch on [Twitter](https://twitter.com/nilswindisch/status/1007536069800333312)   we should support HTTPS on openrefine.org

**Comment by magdmartin** [comment]
Fixed

**Comment by joehand** [comment]
@magdmartin can you also enforce https? That will redirect from http. https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by wetneb** [comment]
Done, thanks!
