### ISSUE TITLE
Unicode support on Regexp

### ISSUE THREAD

**Issue by lapoisse** [OpenRefine/openrefine.github.com#41]
Hello,

As a user, I want to deal with regex facets including accent selection into words. It is  a solution to apply the regex modifier 'u' that would simplify my life. Strangely, it is possible to bypass this limitation using jython into columns creation, but it remains difficult because you have to code each transformation rather using a simple regex modifier. 

As a solution, I wonder if the default modifier u could be used on project based on UTF files... For the moment, very annoying... 

Best regards,

**Comment by wetneb** [comment]
@lapoisse can you submit this issue to our main repository, https://github.com/OpenRefine/OpenRefine? Thanks!
