### ISSUE TITLE
Use standard logo as header

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.github.com#52]
The version of the OpenRefine logo that is used on this website (wireframe version of the diamond) is not used anywhere else. I think OpenRefine's official website should use OpenRefine's official logo! If it does not fit with the rest of the design, then the rest of the design is wrong.

**Comment by AkshadK7** [comment]
Can I work on this issue as it seems that its still not resolved ? @wetneb

**Comment by wetneb** [comment]
Yes please, thanks for volunteering!
