### ISSUE TITLE
Enhance Download page experience (hard to find, unreadable, downplay non-embedded versions)

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.github.com#55]
The download page should be much more prominently displayed in the menu.

On the download page itself, we want to show Windows, Mac and Linux download buttons much more prominently, for the latest stable release. Other releases can be listed elsewhere.

Downloading OpenRefine should be a complete no-brainer.

For instance:
* https://gephi.org/
* https://www.libreoffice.org/

Some people even tweet at us to find the download link! https://twitter.com/rebelsouly/status/1207044835452039168

**Comment by wetneb** [comment]
Detecting the operating system and proposing the appropriate download accordingly would be nice, too. This might require moving out of GitHub pages.

**Comment by trnstlntk** [comment]
Both the Gephi and LibreOffice ones are indeed more advanced and feature-rich than ours, but also a bit bloated IMO. I'd like to keep it as simple as possible.

For me, detecting the operating system is not super necessary, as long as the difference between the versions is very obvious and (indeed) the download links are much clearer.

I would also be in favour of making sure the downloader is - upon clicking the download link - redirected to a 'thank you for downloading; here's how you can support and help OpenRefine' page which includes a donation box.

**Comment by thadguidry** [comment]
Perhaps not worry about detecting the operating system, since someone might use Linux to download their Windows package or vice versa.  And then there's Expat's, VPN's, and all that :-)

**Comment by ostephens** [comment]
Looking at the Gephi/LibreOffice examples the most obvious easiest improvement we could make would be a big "Download OpenRefine now" button as the first thing you see when you get to https://openrefine.org

Then on the Download page again make the main three (or four, but as discussed elsewhere I'm inclined to highlight the Java embedded version for Windows) download options for the current stable release the first or most obvious thing on the page with the other things (and any alternative or older versions) as secondary information either further down the page or on a separate page
