### ISSUE TITLE
Make license clearer

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.github.com#87]
OpenRefine's license should be made clearer on the website. See this thread on our user mailing list where someone could not find our terms of use:
https://groups.google.com/g/openrefine/c/XPZs7UNIUs0

**Comment by thadguidry** [comment]
Once we get CS&S to weigh in on this, then anyone can work on this issue.  Stay tuned as we update the above original comment from the Google Groups thread conversation.

**Comment by wetneb** [comment]
why would we need CS&S to weigh in on this? I am a bit confused…

**Comment by thadguidry** [comment]
Half of the context in the Google Groups thread from the OP is that of EULA, terms, etc.  Where it is still yet unclear if they are looking for our...

"Website terms"
 which is different from
 "OpenRefine license"

**Comment by wetneb** [comment]
I think it is pretty clear that they need OpenRefine's license and not the terms of openrefine.org, but that's just my opinion. In any case, CS&S did not take ownership of IP when onboarding OpenRefine, so I don't think we need to bug them about either OpenRefine's license or the website's terms, no?

**Comment by thadguidry** [comment]
@wetneb Ah, ok, thanks for explaining more fully.  Then yes, I agree, no need for CS&S input here.
